### ISSUE TITLE
怎么解决这个问题ctx.globalCompositeOperation='xor'

### ISSUE THREAD

**Issue by snowcrazy** [cy0707/about_html#42]
##怎么解决这个问题ctx.globalCompositeOperation='xor'啊##

```

<!DOCTYPE html>
<html>
<body>

<canvas id="myCanvas" width="300" height="400" style="border:1px solid #d3d3d3;">
Your browser does not support the HTML5 canvas tag.
</canvas>

<script>

var c=document.getElementById("myCanvas");
var ctx=c.getContext("2d");
ctx.globalCompositeOperation="xor";

ctx.fillStyle="red";
ctx.beginPath();
ctx.moveTo(100,60);
ctx.lineTo(160,120);
ctx.lineTo(100,180);
ctx.lineTo(40,120);
ctx.closePath();
ctx.fill();


ctx.fillStyle="bule";
ctx.beginPath();
ctx.lineTo(160,120);
ctx.lineTo(100,180);
ctx.lineTo(40,120);
ctx.closePath();
ctx.fill();


</script>

</body>
</html>

```

![qq20180915-0](https://user-images.githubusercontent.com/17973701/45585348-8153ba80-b915-11e8-864d-a8a5fc5bc558.png)

**Comment by snowcrazy** [comment]
我的代码都写好了，测试得到这个图片，有bug吧

**Comment by cy0707** [comment]
我问的是，你的问题是什么呢，你想得到什么呢。
你就是说了一句-----我的代码都写好了，测试得到这个图片，有bug吧
正常的流程不是，表达的你的代码是什么意思，你要得到的结果是什么的图呢，为什么结果跟你图不一样。

**Comment by snowcrazy** [comment]
![qq20180915-2](https://user-images.githubusercontent.com/17973701/45586787-dcde7200-b92e-11e8-949a-8d47aa516e61.png)

上面就是我的代码，图片显示有斜线（应该是没有斜线），所以有bug

**Comment by snowcrazy** [comment]
你测试我的代码又发现问题了，Thanks♪(･ω･)ﾉ
