### ISSUE TITLE
Canvas学习笔记之二

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_html#6]
## 绘制线性渐变图形

`var lg = content.createLinearGradient(xStart,yStart,xEnd,yEnd)`

`lg.addColorStop(offset, color)`

* xstart:渐变开始点x坐标
* ystart:渐变开始点y坐标
* xEnd:渐变结束点x坐标
* yEnd:渐变结束点y坐标
*  offset:设定的颜色离渐变结束点的偏移量(0~1)
*  color:绘制时要使用的颜色 

![lineargradient](https://cloud.githubusercontent.com/assets/15865210/20826095/85bda406-b8a3-11e6-8199-004ecc0e5092.png)

```javascript
function draw(){
  var canvas = document.getElementById('draw');
  if (canvas == null) {
    return false;
  }
  var content =canvas.getContext('2d');
  var linearGradient = content.createLinearGradient(0, 0, 0, 300);
  linearGradient.addColorStop(0, '#E0EAFC');
  linearGradient.addColorStop(0.4, '#CFDEF3');
//填充渐变颜色
  content.fillStyle = linearGradient;
//填充图形
  content.fillRect(0, 0, 400, 300);
}
window.onload = function() {
  draw();
}
```

## 径向渐变

`var lg = content.createRadialGradient(xStart,yStart,radiusStart,xEnd,yEnd,radiusEnd)`

`lg.addColorStop(offset, color)`
 

* xStart:发散开始圆心x坐标
* yStart:发散开始圆心y坐标
* radiusStart:发散开始圆的半径
* xEnd:发散结束圆心的x坐标
* yEnd:发散结束圆心的y坐标
* radiusEnd:发散结束圆的半径
* offset:设定的颜色离渐变结束点的偏移量(0~1)
* color:绘制时要使用的颜色

![radialgradient](https://cloud.githubusercontent.com/assets/15865210/20826811/79e512ae-b8a8-11e6-9ee3-89082fdd817f.png)

```javascript
function draw(){
  var canvas = document.getElementById('draw');
  if (canvas == null) {
    return false;
  }
  var content =canvas.getContext('2d');
  var linearGradient = content.createRadialGradient(200, 150, 0, 200,150, 100);
  linearGradient.addColorStop(0, '#E0EAFC');
  linearGradient.addColorStop(0.4, '#CFDEF3');
  content.fillStyle = linearGradient;
  content.beginPath();
  content.arc(200, 150, 100, 0, Math.PI*2, true);
  content.closePath();
  content.fill();
}
window.onload = function() {
  draw();
}
```

#### 坐标变换

* 平移： 使用图形上下文对象的translate方法移动坐标轴原点。

`content.translate(x, y)`-----x代表将坐标轴原点向右移动多少个单位，默认情况下为像素；y代表将坐标轴原点向下移动多少个单位。

* 扩大：使用图形上下文对象的scale方法将图形放大。

`content.scale(x, y)`-----x代表是水平方向放大的倍数，y是垂直方向的放大的倍数。将图形缩小的时候，将这两个参数设置为0到1之间的小数就可以了。

* 旋转：使用图形上下文对象的rotate方法将图形进行旋转。

`content.rotate(angle)`---angel是指旋转的角度。旋转中心店是坐标轴的原点。旋转是以顺时针方向进行的，要想逆时针旋转时，将angle设定为负数。

```javascript
function draw(){
  var canvas = document.getElementById('draw');
  if (canvas == null) {
    return false;
  }
  var content =canvas.getContext('2d');
  content.fillStyle = '#eef';
  content.fillRect(0, 0, 400, 300);
// 图形绘制，移动的是坐标原点
  content.translate(200, 50);
  content.fillStyle = 'rgba(255, 0, 0, 0.25)';
  for (var i = 0; i < 50; i++) {
    content.translate(25, 25);
    content.scale(0.95, 0.95);
    content.rotate(Math.PI/10);
    content.fillRect(0, 0, 100, 50);
  }
}
window.onload = function() {
  draw();
}
```
   

得到如下图形：

![can](https://cloud.githubusercontent.com/assets/15865210/20827290/fdd9af2c-b8ab-11e6-85b3-3c3faf79345c.png)

#### 坐标变换与路径的结合使用

如果对矩形进行变形，使用坐标变换就足够了。但是对使用路径绘制出来的图形进行变换的时候，要考虑的事件就比较多了。因为使用了坐标变换之后，已经创建好的路径就不能用了。必须重新创建路径。重新创建好路径之后，坐标变换方法又失效了。

**此时，必须先另写一个创建路径的函数，然后在坐标变换的同时调用该函数。**

```javascript
function draw(){
  var canvas = document.getElementById('draw');
  if (canvas == null) {
    return false;
  }
  var content =canvas.getContext('2d');
  content.fillStyle = '#eef';
  content.fillRect(0, 0, 400, 300);
// 图形绘制
  content.translate(200, 50);
  content.fillStyle = 'rgba(255, 0, 0, 0.25)';
  for (var i = 0; i < 50; i++) {
    content.translate(25, 25);
    content.scale(0.95, 0.95);
    content.rotate(Math.PI/10);
    // 画五角星。坐标变换同时调用函数
    create5Star(content);
    content.fill();
  }
}
function create5Star(content) {
  var n = 0,
      dx =100,
      dy = 0,
      s = 50;
  // 创建路径
  content.beginPath();
  content.fillStyle = 'rgba(255, 0, 0, .5)';
  var x = Math.sin(0);
  var y = Math.cos(0);
  var dig = Math.PI/5*4;
  for (var i = 0; i < 5; i++) {
    var x = Math.sin(i*dig);
    var y = Math.cos(i*dig);  
    content.lineTo(dx + x*s, dy + y*s);
  }
  content.closePath();
}
window.onload = function() {
  draw();
}
```
![can2](https://cloud.githubusercontent.com/assets/15865210/20827582/f2ab093c-b8ad-11e6-8240-8484c8ec9eec.png)

#### 矩形变换

` content.transform(m11,m12,m21,m22,dx,dy)`

  所谓的矩阵变换其实是content内实现平移，缩放，旋转的一种机制，主要原理就是矩阵相乘。

 
* context.translate(x,y) 等同于context.transform (1,0,0,1,x,y)或context.transform(0,1,1,0.x,y)
* context.scale(x,y)等同于context.transform(x,0,0,y,0,0)或context.transform (0,y,x,0, 0,0);
* context.rotate(θ)等同于context.transform(Math.cos(θ*Math.PI/180)，Math.sin(θ*Math.PI/180), -Math.sin(θ*Math.PI/180),Math.cos(θ*Math.PI/180)，0，0）或 context.transform(-Math.sin(θ*Math.PI/180),Math.cos(θ*Math.PI/180)，Math.cos(θ*Math.PI/180)，Math.sin(θ*Math.PI/180), 0，0）

## 图形组合

我们可以将一个人图形重叠绘制在另一个图形上面。但是图形中能够被看到的部分完全取决于图形的绘制顺序。有时候想将两个图形进行组合，并且自己决定以那种方式进行组合，这是。就需要使用图形上下文对象的globalCompositeOperation属性决定自己的组合方式。

`content.globalCompositeOperation = type`

type的值必须是下面几种字符串之一

* source-over（默认值）:新图形覆盖在原图形之上

* destination-over: 在原有图形下绘制新图形

* source-in:显示原有图形和新图形的交集，新图形在上，所以颜色为新图形的颜色

* destination-in:显示原有图形和新图形的交集，原有图形在上，所以颜色为原有图形的颜色

* source-out:只显示新图形非交集部分

* destination-out:只显示原有图形非交集部分

* source-atop:显示原有图形和交集部分和未被重叠覆盖的原有图形，新图形在上，所以交集部分的颜色为新图形的颜色。

* destination-atop:只绘制原有图形中被新图形覆盖的部分，与新图形的其他部分。原有图形中的其他部分变成透明。不绘制新图形中与原图形相重叠的部分。

* lighter:原有图形和新图形都显示，交集部分做颜色叠加

* xor:只绘制新图形中与原图形不重叠的部分，重叠部分变成透明。

* copy:只绘制新图形，原有图形中未与新图形重叠的部分变成透明。

这是参考文章里的。大家可以根据图形进行理解。

```javascript
function draw(){
  var canvas = document.getElementById('draw');
  if (canvas == null) {
    return false;
  }
  var content =canvas.getContext('2d');
   var oprtns = new Array(
    "source-over",
    "destination-over",
  "source-in",
  "destination-in",
  "source-out",
  "destination-out",
  "source-atop",
  "destination-atop",
  "lighter",
   "xor",         
  "copy"
   );
  var i = 0;//组合效果编号

  //结合setinterval动态显示组合
  var interal = setInterval(function () {
      if (i == 10) {
          i=0;
      }
      else {
          i++;
      }
      //蓝色矩形
      content.fillStyle = "blue";
      content.fillRect(10, 10, 60, 60);
      //设置组合方式 
      content.globalCompositeOperation = oprtns[i];
      //设置新图形（红色圆形）
    content.beginPath();
    content.fillStyle = "red";
      content.arc(60, 60, 30, 0, Math.PI * 2, false);
      content.fill();
 }, 1000);
              
}
window.onload = function() {
  draw();
}
```

#### globalAlpha(	设置或返回绘图的当前 alpha 或透明值)

* globalAlpha 属性设置或返回绘图的当前透明值（alpha 或 transparency）。
* globalAlpha 属性值必须是介于 0.0（完全透明） 与 1.0（不透明） 之间的数字。

例如：首先，绘制一个红色的矩形，然后将透明度 (globalAlpha) 设置为 0.5，然后再绘制一个蓝色和一个绿色的矩形：

```javascript
var c=document.getElementById("myCanvas");
var ctx=c.getContext("2d");
ctx.fillStyle="red";
ctx.fillRect(20,20,75,50);
// Turn transparency on
ctx.globalAlpha=0.2;
ctx.fillStyle="blue"; 
ctx.fillRect(50,50,75,50); 
ctx.fillStyle="green"; 
ctx.fillRect(80,80,75,50);
```

![alpha](https://cloud.githubusercontent.com/assets/15865210/20915576/c82466ce-bbc1-11e6-854d-4255d20f8a56.png)

## 给图形绘制阴影

* context.shadowOffsetX :阴影的横向位移量（默认值为0）
* context.shadowOffsetY :阴影的纵向位移量（默认值为0）
* context.shadowColor :阴影的颜色
* context.shadowBlur :阴影的模糊范围（值越大越模糊）

```javascript
function draw(){
  var canvas = document.getElementById('draw');
  if (canvas == null) {
    return false;
  }
  var content =canvas.getContext('2d');
    content.shadowOffsetX = 10;
    content.shadowOffsetY = 10;
    content.shadowColor = 'rgba(100,100,100,0.5)';
    content.shadowBlur = 1.5;
    content.fillStyle = 'rgba(255,0,0,0.5)';
    content.fillRect(100, 100, 200, 100);
              
}
window.onload = function() {
  draw();
}
```

**Comment by snowcrazy** [comment]
老师，我有重点bug，怎么解决这个问题ctx.globalCompositeOperation='xor'啊？

```

<!DOCTYPE html>
<html>
<body>

<canvas id="myCanvas" width="300" height="400" style="border:1px solid #d3d3d3;">
Your browser does not support the HTML5 canvas tag.
</canvas>

<script>

var c=document.getElementById("myCanvas");
var ctx=c.getContext("2d");
ctx.globalCompositeOperation="xor";  // 这个重点bug

ctx.fillStyle="red";
ctx.beginPath();
ctx.moveTo(100,60);
ctx.lineTo(160,120);
ctx.lineTo(100,180);
ctx.lineTo(40,120);
ctx.closePath();
ctx.fill();


ctx.fillStyle="bule";
ctx.beginPath();
ctx.lineTo(160,120);
ctx.lineTo(100,180);
ctx.lineTo(40,120);
ctx.closePath();
ctx.fill();


</script>

</body>
</html>
<!DOCTYPE html>
<html>
<body>

<canvas id="myCanvas" width="300" height="400" style="border:1px solid #d3d3d3;">
Your browser does not support the HTML5 canvas tag.
</canvas>

<script>

var c=document.getElementById("myCanvas");
var ctx=c.getContext("2d");
ctx.globalCompositeOperation="xor";

ctx.fillStyle="red";
ctx.beginPath();
ctx.moveTo(100,60);
ctx.lineTo(160,120);
ctx.lineTo(100,180);
ctx.lineTo(40,120);
ctx.closePath();
ctx.fill();


ctx.fillStyle="bule";
ctx.beginPath();
ctx.lineTo(160,120);
ctx.lineTo(100,180);
ctx.lineTo(40,120);
ctx.closePath();
ctx.fill();


</script>

</body>
</html>

```

![qq20180915-0](https://user-images.githubusercontent.com/17973701/45584957-0ab3be80-b90f-11e8-9e2e-dd8b4bf86fd1.png)
#

**Comment by cy0707** [comment]
参考前一篇回复
